routes/web.php
<?php

use App\Models\Invoice;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ParcelController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\DropOffController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CompanySettingController;
use App\Http\Controllers\ReportController;
use SebastianBergmann\CodeCoverage\Report\Xml\Report;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::group(['middleware' => ['auth']], function() {

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');


    Route::resource('status',StatusController::class)->except('create','edit','show');
    Route::resource('dropOff',DropOffController::class)->except('create','edit','show');
    Route::resource('client',ClientController::class)->except('create','edit','show');
    Route::resource('product',ProductController::class)->except('create','edit','show');
    Route::resource('invoice',InvoiceController::class);
    Route::post('get-client-data',[InvoiceController::class,'getClient'])->name('invoice.getClient');
    // Route::resource('parcel',ParcelController::class);

    // Report
    Route::get('report/product',[ReportController::class,'product'])->name('report.product');
    Route::get('report/invoice',[ReportController::class,'invoice'])->name('report.invoice');
    // Report





    Route::resource('roles', RoleController::class);
    Route::resource('user', UserController::class);
    Route::get('settings/company-settings', [CompanySettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company-setting', [CompanySettingController::class, 'updateCompanySetting'])->name('company.update');
});

Route::get('migrate',function(){
    Artisan::call('migrate');
    dd('done');
});

// Route::get('migrate-fresh',function(){
//     Artisan::call('migrate:fresh --seed');
// });

Route::get('optimize',function(){
    Artisan::call('optimize');
    Artisan::call('optimize:clear');
    dd('done');
});

Route::get('seed',function(){
    Artisan::call('db:seed', [
        '--class' => CountrySeeder::class
    ]);
});

Route::get('rollback',function(){
    Artisan::call('migrate:rollback --step=3');
    dd('done');
});

Route::get('storage-link',function(){
    Artisan::call('storage:link');
    dd('done');
});

// Route::get('drop',function(){
//     Schema::dropIfExists('contacts');
//     dd('done');
// });

require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->checkPermission('role.access');
        $roles = Role::orderBy('id','DESC')->paginate($this->itemPerPage);
        $permissions = Permission::pluck('name','id');
        $this->putSL($roles);
        return view('dashboard.role.index',compact('roles','permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->checkPermission('role.create');
        $permission = Permission::pluck('name','id');
        return view('dashboard.role.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->checkPermission('role.store');
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $this->checkPermission('role.show');
        return view('dashboard.role.show',compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->checkPermission('role.edit');
        $permission = Permission::pluck('name','id');

        return view('dashboard.role.edit',compact('role','permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->checkPermission('role.update');
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->checkPermission('role.destroy');
        $role->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

resources/views/dashboard/role/create.blade.php
@extends('layouts.master')

@section('title', 'Role|Create')


@section('content')
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0">Create Role</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Role</a></li>
                        <li class="breadcrumb-item active">Create Role</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row d-flex justify-content-center">
        <div class="col-9">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">

                {{ Form::open(['route' => 'roles.store']) }}
                <div class="card-body">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} mb-3">
                        {{ Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) }}
                        <div class="col-sm-9">
                            {{ Form::text('name', null, ['class' => 'form-control','placeholder' => 'Enter name',
                            'required' => 'required']) }}
                            <small class="text-danger">{{ $errors->first('name') }}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('permission') ? ' has-error' : '' }} mb-3">
                        {{ Form::label('permission', 'permission', ['class' => 'col-sm-3 control-label']) }}
                        <div class="col-sm-9">
                            {{ Form::select('permission[]', $permission, null, ['class' => 'form-control
                            select2','multiple'=>'multiple', 'required' => 'required']) }}
                            <small class="text-danger">{{ $errors->first('permission') }}</small>
                        </div>
                    </div>


                    <div class="mt-5">
                        <button type="submit" class="btn btn-primary w-md">Submit</button>
                    </div>
                </div>

                {{ Form::close() }}
            </div>
        </div> <!-- end col -->
    </div>
    <!-- end row -->
</div>
@endsection

resources/views/dashboard/role/edit.blade.php
@extends('layouts.master')

@section('title', 'Role|Edit')


@section('content')
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0">Edit Role</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Role</a></li>
                        <li class="breadcrumb-item active">Edit Role</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row d-flex justify-content-center">
        <div class="col-9">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">

                {{ Form::model($role, ['route' => ['roles.update', $role->id], 'method' => 'PUT', 'class' =>
                'form-horizontal']) }}
                <div class="card-body">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} mb-3">
                        {{ Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) }}
                        <div class="col-sm-9">
                            {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Enter name',
                            'required' => 'required']) }}
                            <small class="text-danger">{{ $errors->first('name') }}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('permission') ? ' has-error' : '' }} mb-3">
                        {{ Form::label('permission', 'permission', ['class' => 'col-sm-3 control-label']) }}
                        <div class="col-sm-9">
                            {{ Form::select('permission[]', $permission, $role->permissions, ['class' => 'form-control
                            select2','multiple'=>'multiple', 'required' => 'required']) }}
                            <small class="text-danger">{{ $errors->first('permission') }}</small>
                        </div>
                    </div>


                    <div class="mt-5">
                        <button type="submit" class="btn btn-primary w-md">Submit</button>
                    </div>
                </div>
                {{ Form::close() }}



            </div>
        </div> <!-- end col -->
    </div>
    <!-- end row -->



</div>
@endsection

resources/views/dashboard/role/form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} mb-3">
    {{ Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) }}
    <div class="col-sm-9">
        {{ Form::text('name', null, ['class' => 'form-control','placeholder' => 'Enter name',
        'required' => 'required']) }}
        <small class="text-danger">{{ $errors->first('name') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('permission') ? ' has-error' : '' }} mb-3">
    {{ Form::label('permission', 'permission', ['class' => 'col-sm-3 control-label']) }}
    <div class="col-sm-9">
        {{ Form::select('permission[]', $permissions, null, ['class' => 'select2 form-control ','multiple'=>'multiple', 'required' => 'required']) }}
        <small class="text-danger">{{ $errors->first('permission') }}</small>
    </div>
</div>

resources/views/dashboard/role/index.blade.php
@extends('layouts.master')

@section('title', 'Role')


@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0">role</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">role</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-4">
                            <div class="d-flex justify-content-end">
                                <a class="btn btn-primary btn-md waves-effect waves-light" href="{{ route('roles.create') }}">Create</i></a>
{{--                                <button type="button" class="btn btn-primary btn-md waves-effect waves-light"--}}
{{--                                        data-bs-toggle="modal" data-bs-target="#create">Create</button>--}}
{{--                                <!-- sample modal content -->--}}
{{--                                <div id="create" class="modal fade" tabindex="-1" role="dialog"--}}
{{--                                     aria-labelledby="createLabel" aria-hidden="true">--}}
{{--                                    <div class="modal-dialog">--}}
{{--                                        <div class="modal-content">--}}
{{--                                            <div class="modal-header">--}}
{{--                                                <h5 class="modal-title" id="createLabel">Create role</h5>--}}
{{--                                                <button type="button" class="btn-close" data-bs-dismiss="modal"--}}
{{--                                                        aria-label="Close"></button>--}}
{{--                                            </div>--}}
{{--                                            {{ Form::open(['route' => 'roles.store', 'class' => 'needs-validation', 'novalidate']) }}--}}
{{--                                            <div class="modal-body">--}}
{{--                                                @if ($errors->any())--}}
{{--                                                    <div class="alert alert-danger">--}}
{{--                                                        <ul>--}}
{{--                                                            @foreach ($errors->all() as $error)--}}
{{--                                                                <li>{{ $error }}</li>--}}
{{--                                                            @endforeach--}}
{{--                                                        </ul>--}}
{{--                                                    </div>--}}
{{--                                                @endif--}}
{{--                                                @include('dashboard.role.form')--}}
{{--                                            </div>--}}
{{--                                            <div class="modal-footer">--}}
{{--                                                <button type="button" class="btn btn-secondary waves-effect"--}}
{{--                                                        data-bs-dismiss="modal">Close</button>--}}
{{--                                                <button type="submit"--}}
{{--                                                        class="btn btn-primary waves-effect waves-light">Create</button>--}}
{{--                                            </div>--}}
{{--                                            {{ Form::close() }}--}}
{{--                                        </div><!-- /.modal-content -->--}}
{{--                                    </div><!-- /.modal-dialog -->--}}
{{--                                </div><!-- /.modal -->--}}
                            </div>
                        </div>
                        <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap">
                            <thead>
                            <tr>
                                <th>{{ __('ID')}}</th>
                                <th>{{ __('Name') }}</th>
                                <th class="action">{{ __('Action') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($roles as $role)
                                <tr>
                                    <td>{{ $role->sl}}</td>
                                    <td>{{ $role->name }}</td>
                                    <td nowrap="nowrap">
                                         <a class="btn btn-primary btn-md waves-effect waves-light" href="{{ route('roles.edit', $role->id) }}"><i class="fas fa-edit"></i></a>
                                        {{-- Edit Modal --}}
{{--                                        <button type="button" onclick="editData({{$role->id}})" class="btn btn-primary btn-md waves-effect waves-light"--}}
{{--                                                data-bs-toggle="modal" data-bs-target="#edit{{$role->id}}"><i--}}
{{--                                                class="fas fa-edit"></i></button>--}}
                                        <!-- sample modal content -->
                                        <div id="edit{{$role->id}}" class="modal fade" tabindex="-1" role="dialog"
                                             aria-labelledby="editLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="editLabel">Edit role</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                                aria-label="Close"></button>
                                                    </div>
                                                    {{ Form::model($role, ['route' => ['roles.update', $role->id], 'method' => 'PUT', 'class' => 'needs-validation', 'novalidate']) }}
                                                    <div class="modal-body">
                                                        @if ($errors->any())
                                                            <div class="alert alert-danger">
                                                                <ul>
                                                                    @foreach ($errors->all() as $error)
                                                                        <li>{{ $error }}</li>
                                                                    @endforeach
                                                                </ul>
                                                            </div>
                                                        @endif
                                                        @include('dashboard.role.form')
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary waves-effect"
                                                                data-bs-dismiss="modal">Close</button>
                                                        <button type="submit"
                                                                class="btn btn-primary waves-effect waves-light">Update</button>
                                                    </div>
                                                    {{ Form::close() }}
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        {{ Form::open(['method' => 'DELETE', 'route' => ['roles.destroy', $role->id], 'style' => 'display:inline']) }}
                                        {{ Form::button('<i class="fas fa-trash"  aria-hidden="true"></i>', ['class' => 'btn btn-danger btm-md', 'type' => 'submit']) }}
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
@endsection
@push('style')
    <style>
        .action {
            width: 120px;
        }
    </style>
@endpush
@push('script')
    <script src="{{ asset('') }}assets/js/pages/form-validation.init.js"></script>
    <script>
        $('.select2').select2({
            dropdownParent: $('#create'),
            placeholder: "Select a state",
        });

        function editData(id){
            let data = $('#edit'+id)
            $('.select2').select2({
                dropdownParent: data,
                placeholder: "Select Options",
            });
            console.log(data)
        }
    </script>


@endpush