routes/web.php
<?php

use App\Models\Invoice;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ParcelController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\DropOffController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CompanySettingController;
use App\Http\Controllers\ReportController;
use SebastianBergmann\CodeCoverage\Report\Xml\Report;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::group(['middleware' => ['auth']], function() {

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');


    Route::resource('status',StatusController::class)->except('create','edit','show');
    Route::resource('dropOff',DropOffController::class)->except('create','edit','show');
    Route::resource('client',ClientController::class)->except('create','edit','show');
    Route::resource('product',ProductController::class)->except('create','edit','show');
    Route::resource('invoice',InvoiceController::class);
    Route::post('get-client-data',[InvoiceController::class,'getClient'])->name('invoice.getClient');
    // Route::resource('parcel',ParcelController::class);

    // Report
    Route::get('report/product',[ReportController::class,'product'])->name('report.product');
    Route::get('report/invoice',[ReportController::class,'invoice'])->name('report.invoice');
    // Report





    Route::resource('roles', RoleController::class);
    Route::resource('user', UserController::class);
    Route::get('settings/company-settings', [CompanySettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company-setting', [CompanySettingController::class, 'updateCompanySetting'])->name('company.update');
});

Route::get('migrate',function(){
    Artisan::call('migrate');
    dd('done');
});

// Route::get('migrate-fresh',function(){
//     Artisan::call('migrate:fresh --seed');
// });

Route::get('optimize',function(){
    Artisan::call('optimize');
    Artisan::call('optimize:clear');
    dd('done');
});

Route::get('seed',function(){
    Artisan::call('db:seed', [
        '--class' => CountrySeeder::class
    ]);
});

Route::get('rollback',function(){
    Artisan::call('migrate:rollback --step=3');
    dd('done');
});

Route::get('storage-link',function(){
    Artisan::call('storage:link');
    dd('done');
});

// Route::get('drop',function(){
//     Schema::dropIfExists('contacts');
//     dd('done');
// });

require __DIR__.'/auth.php';

resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> <a href="https://niloydas.net/" target="blank"> © Niloy Das.</a>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Crafted with <i class="mdi mdi-heart text-danger"></i> by MRBDL
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/leftside-nav.blade.php
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>

                <li>
                    <a href="{{route('dashboard')}}" class="waves-effect {{ request()->is('dashboard') ? 'mm-active' : null }}">
                        <i class="mdi mdi-home-variant-outline"></i>
                        <span>Dashboard</span>
                    </a>
                </li>


                @can('invoice.access')
                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect">
                            <i class="mdi mdi-file-alert-outline"></i>
                            <span>Invoice</span>
                        </a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><a href="{{route('invoice.index')}}">All Invoice</a></li>
                            <li><a href="{{route('invoice.create')}}">Create Invoice</a></li>
                        </ul>
                    </li>
                @endcan
                @can('report.access')
                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect">
                            <i class="mdi mdi-file-alert-outline"></i>
                            <span>Report</span>
                        </a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><a href="{{route('report.product')}}">Product</a></li>
                            <li><a href="{{route('report.invoice')}}">Invoice</a></li>
                        </ul>
                    </li>
                @endcan

                @can('product.access')
                <li>
                    <a href="{{route('product.index')}}" class="waves-effect {{ request()->is('product') ? 'mm-active' : null }}">
                        <i class="mdi mdi-account-box-multiple-outline"></i>
                        <span>Product</span>
                    </a>
                </li>
                @endcan
                @can('client.access')
                <li>
                    <a href="{{route('client.index')}}" class="waves-effect {{ request()->is('client') ? 'mm-active' : null }}">
                        <i class="mdi mdi-account-box-multiple-outline"></i>
                        <span>Client</span>
                    </a>
                </li>
                @endcan
                @can('dropOff.access')
                <li>
                    <a href="{{route('dropOff.index')}}" class="waves-effect {{ request()->is('dropOff') ? 'mm-active' : null }}">
                        <i class="mdi mdi-map-marker-check-outline"></i>
                        <span>Drop Off Location</span>
                    </a>
                </li>
                @endcan
                @can('status.access')
                <li>
                    <a href="{{route('status.index')}}" class="waves-effect {{ request()->is('status') ? 'mm-active' : null }}">
                        <i class="mdi mdi-bell"></i>
                        <span>Status</span>
                    </a>
                </li>
                @endcan
                <li class="menu-title">Settings</li>
                @can('user.access')
                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect {{ request()->is('user*') ? 'mm-active' : null }}">
                            <i class="mdi mdi-cog-outline"></i>
                            <span>Users</span>
                        </a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><a href="{{route('user.index')}}">All User</a></li>
                            <li><a href="{{route('user.create')}}">Create User</a></li>
                            <li><a href="{{route('roles.index')}}">User Roles</a></li>
                        </ul>
                    </li>
                @endcan

                @can('settings.access')
                    <li>
                        <a href="{{ route('company.edit') }}"
                            class="waves-effect {{ request()->is('settings/company-settings') ? 'mm-active' : null }}">
                            <i class="mdi mdi-cog-outline"></i>
                            <span>Company Setting</span>
                        </a>
                    </li>
                @endcan
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>

resources/views/includes/rightside-bar.blade.php
<div class="right-bar">
    <div data-simplebar class="h-100">
        <div class="rightbar-title d-flex align-items-center px-3 py-4">

            <h5 class="m-0 me-2">Settings</h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class="mt-0" />
        <h6 class="text-center mb-0">Choose Layouts</h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="{{asset('/')}}assets/images/layouts/layout-1.png" class="img-thumbnail" alt="layout-1">
            </div>

            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch" checked>
                <label class="form-check-label" for="light-mode-switch">Light Mode</label>
            </div>

            <div class="mb-2">
                <img src="{{asset('/')}}assets/images/layouts/layout-2.png" class="img-thumbnail" alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="dark-mode-switch" data-bsStyle="{{asset('/')}}assets/css/bootstrap-dark.min.css" data-appStyle="{{asset('/')}}assets/css/app-dark.min.css">
                <label class="form-check-label" for="dark-mode-switch">Dark Mode</label>
            </div>

            <div class="mb-2">
                <img src="{{asset('/')}}assets/images/layouts/layout-3.png" class="img-thumbnail" alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox" id="rtl-mode-switch" data-appStyle="{{asset('/')}}assets/css/app-rtl.min.css">
                <label class="form-check-label" for="rtl-mode-switch">RTL Mode</label>
            </div>


        </div>

    </div> <!-- end slimscroll-menu-->
</div>